{
   "ad_priority":[
      "admob",
      "facebook",
      "unity",
      "appLovin",
      "any"
   ],
   "banner_ad_priority":[
      "admob",
      "facebook",
      "unity",
      "appLovin",
      "any"
   ],
   "interstitial_ad_count":4,
   "is_ios_approving":false,
   "is_android_approving":false
}
